-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: db/push_history.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/push_history (
  ph_page INTEGER NOT NULL, ph_user INTEGER NOT NULL,
  ph_target BLOB NOT NULL, ph_timestamp BLOB NOT NULL
);
